spring.application.name=${APP_NAME:Ecommerce_Application}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/ecommercedatabasee}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:2395}
spring.datasource.driver-class-name=${DB_DRIVER:com.mysql.cj.jdbc.Driver}

spring.jpa.hibernate.ddl-auto=${HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${HIBERNATE_SHOW_SQL:true}
spring.jpa.properties.hibernate.dialect=${HIBERNATE_DIALECT:org.hibernate.dialect.MySQL8Dialect}

spring.thymeleaf.prefix=${THYMELEAF_PREFIX:classpath:/templates/}
spring.thymeleaf.suffix=${THYMELEAF_SUFFIX:.html}
spring.thymeleaf.mode=${THYMELEAF_MODE:HTML}
spring.thymeleaf.encoding=${THYMELEAF_ENCODING:UTF-8}

aws.s3.bucket.name=${AWS_S3_BUCKET_NAME:ecommproject}
aws.s3.region=${AWS_S3_REGION:us-east-1}
aws.accessKeyId=${AWS_ACCESS_KEY:AKIA2YICAVFERR3COKGL}
aws.secretAccessKey=${AWS_SECRET_KEY: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}

server.port=${SERVER_PORT:9090}

razorpay.key.id=${RAZORPAY_KEY_ID:rzp_test_H8fYLmO3B3OKIu}
razorpay.key.secret=${RAZORPAY_KEY_SECRET:oVORLicN5rZkatFOdWtveYI6}